### ISSUE TITLE
transformer-remark content shows up as markdown

### ISSUE THREAD

**Issue by cco3** [Microflash/gridsome-plugin-feed#5]
Using source-filesystem and transformer-remark, I can do a query and get back html content.  However, when I generate a feed with gridsome-plugin-feed, it shows up as markdown.

**Comment by naiyerasif** [comment]
This is currently the limitation of Gridsome's API; it does not return the transformed HTML as a part of `node` object. You can use the workaround [described here](https://github.com/gridsome/gridsome/issues/514#issuecomment-510481670).
